### ISSUE TITLE
Remove node_modules from GH

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-analytics#2]
Node modules are not meant to be in GH repository. for every new person when to clone this app. it takes time to download NPM packages from GH, which supposed to install through yarn or npm.

It's better not to send such stuff to GH.

e.g
node modules.
priv/static builds

**Comment by marcoherbst** [comment]
@ijunaid8989 @Ali7862 

Good that you see that.

That is the purpose of involving Ali & Team PK in this project > spotting these things and helping Ilias , so good, standardisation is important.

**Comment by elyas20** [comment]
Thanks for noticing that Junaid.
